let nombreDeSuperHeroe = 'Batman';
let nombre = 'Bruce Wayne';
let vuela = 'vuela';
let maneja = 'si';
let vida = '0 a 100';
let trabajo = undefined;
let tiempoLibre = null;
console.log('Nombre de SuperHeroe '+nombreDeSuperHeroe);
console.log('Nombre '+vuela);
console.log('Vuela '+vuela);
console.log('Maneja '+maneja);
console.log('Vida '+vida);
console.log('Trabajo '+trabajo);
console.log('Tiempo libre '+tiempoLibre);
console.log('Nombre de superheroe'+typeof nombreDeSuperHeroe);
console.log('Nombre '+typeof nombre);
console.log('Vuela '+typeof vuela);
console.log('Maneja '+typeof maneja);
console.log('Vida '+typeof vida);
console.log('Trabajo '+typeof trabajo);
console.log('Tiempo libre '+typeof tiempoLibre);