let cantidadDeUsuarios = 100;
console.log('Cantidad de usuarios: ' + cantidadDeUsuarios);
let cantidadDeUsuarios += 5;
console.log('Cantidad de usuarios: ' + cantidadDeUsuarios);
let cantidadDeUsuarios -=3;
console.log('Cantidad de usuarios' + cantidadDeUsuarios);
let cantidadDeUsuarios *=2;
console.log('Cantidad de usuarios' + cantidadDeUsuarios);
let cantidadDeUsuarios /= 2;
console.log('Cantidad de usuarios ' + cantidadDeUsuarios);